### ISSUE TITLE
What is the community license good for?

### ISSUE THREAD

**Issue by luis-cortina** [Anyline/anyline-dotnet-examples#1]
Hi guys:

I want to implement a free ios/android app and reading through the license I wasn't sure wheter that is allowed or not?
Can you please clarify? 

Thanks,

Luis

**Comment by ricardocolombo** [comment]
Hi luis,

Sorry for the dalay. We don't actively monitor the GitHub Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

Thank you so much!
